const express = require('express');
const app = express();
const dotenv = require('dotenv');
const connectDB = require('./config/db');
const postRoutes = require('./routes/postRoutes');
dotenv.config();
connectDB();
app.use(express.json());
app.use(cors());
app.use('/api/posts', postRoutes);
const PORT = process.env.PORT || 6000;
app.listen(PORT, () => console.log('Server on ${PORT}'));